# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "kzQ/VQLFTV889pltIE+uKytjUPEkJWuKR/E8wphBsYoiH7AwNj37XaEXKlXoA4DrGQyS0fM0VmF5qFTF7+lV+p0aJny7aor4Zevqpp5pPjaOlSvpxF2P8fUMviqLEkyLWzBynlrXye8s5HCZprHyvL2+MAjVXt4ELURaw7VXqNb+v2uT4bV/uPRODgjJwGi+O3e8VdXxgdB7MJytE29X5pkF0rxVtw9/j40swXkMj8haRL+LhXvJDx7uDeIROnLY2h0NvciKdU0QnMs9ToabMhfQ2Ye81ILVE2m6/s/pp9XY11UdmJBjElo3X0X7Gsb4appl5nfNrF4AMMIbPU4VXryJAl0sqESmP8ldD9mqQJTca4EBHBasNzZHry3FERuZrEAMcXbSKCLtUUDh/z1OCr74zdRE3DuZGJXyI5SyAwd0xDdVMsd1moGJGcSyBLMzTPbMzCBRmVGblbT1GMPbv+tb/dO3H3l3CI/ObmaaD7mimEevg9ysuTCu5jyEzh7AapO36wJmWNiaqKWmUodD0H5JzxkZM/SFxM0/TYDxsdvBZIgD/PjkIYGIR+K8T8daB4gAc6VSTjsc7EH1aVDm2izbqaNC4lVljuz5Zm4LrbztEv/fX6SNPtceoLy5ekuD+3RXNRB1UJ4fLIq492DnxD+xzffw5pUnRCSs9mwi/xo="


before_install:
    - brew remove --force $(brew list)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda update --yes conda
      conda install --yes conda-build jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
