travis:
  secure:
    BINSTAR_TOKEN: KWVoWCaHyX1v6ZVMLmOjZXEnO8Ob8PdxPW8+3VBwxDcze6PD11NkTnJ/9BBtufFhvsYo2RyfsAIlkWNPY9MMMxKxn8DdsLANtcfl/sf2RKSAgvGA4rgI3Y82RUeIvFyaOMDi9SqAt8/pxKRb7GLOEHY0t9RuO0loF2/vj4C/9LqWK5OW3+LqKQpsNJ1pvy0DJEG+OwIE2ACYFIWClSjbT5bghYTKTVMtRp7nwH42Nn9Om7zHOzFQheeNVMkzmKKvwwrAuiaFmA+l0SpCr7oSuxwpQIq3Lzdjk7J3lnR2UfgL/FGO+pB44BTc0fbIufDiAiUhfcghe5XAqqg3E/Eud2XWRgllf+WnCh9m3z2KHtVjI2TrcPdaRE3pKYkCkZCgnej95NvE2/HvIgZQJp/CL3gKk0kgnt/U645NIRrvtRSLMgqOHzTi0pKKI4mYkrQOUVejN1su12brQJOsEnUJuQwAUcQ2+JY6/pUohRqftsO3gDfKnSuNDGlwiBDSZOhr8fgG/ZA9tbNRkothicAGinYN9m54JixZxczGNYOqAtcPOHBFm0stWIIdt4et813eBppZLQhI2gnzICn77LPsX+QyZX/CcIDOALN6mTlckPadwirgRCQikKPORTBuIHa1YvoZMbQZ/0m1G7pjo/3wyiJr1oFxJqojZiHtCjrbn6Y=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
